### ISSUE TITLE
20045 error 

### ISSUE THREAD

**Issue by helloplauz10** [Canny1913/miunlock#23] opened 2023-02-12 00:47 UTC
I tried updating the version but still dint work. I use a rooted device (Linux)
![Screenshot_20230212-083535](https://user-images.githubusercontent.com/105611677/218287251-57044601-aa78-451b-9b82-20c26ea849e0.png)

**Comment by Recognizer83** [comment] 2023-02-16 05:32
getting same error

**Comment by JarrerLog** [comment] 2023-04-30 01:30
> I tried updating the version but still dint work. I use a rooted device (Linux) ![Screenshot_20230212-083535](https://user-images.githubusercontent.com/105611677/218287251-57044601-aa78-451b-9b82-20c26ea849e0.png)

Like me but I run on Kali Linux on laptop I can't figure out how to fix it need help Publishers

**Comment by Canny1913** [comment] 2023-08-25 13:23
duplicate of: https://github.com/Canny1913/miunlock/issues/3
ill debug this after im done updating the tool

**Closed by Canny1913** 2023-08-25 13:23 UTC
